apiVersion: v1
kind: ReplicationController
metadata:
  name: node-gulp
  labels:
    name: node-gulp
spec:
  replicas: 1
  selector:
    name: node-gulp
  template:
    metadata:
      labels:
        name: node-gulp
    spec:
      containers:
      - name: node-gulp
        image: astorga/node-gulp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
